### PR TITLE
Replace all `require` with `import` in tests. Fix uncovered errors minimally.

### LINKED ISSUE #282: Using dynamic `require` instead of `import` in tests hides typescript errors.
The tests use `require('...')` to import from the library, and it's using a dynamically calculated variable from the environment to determine the path. This is hiding a lot of Typescript errors that currently exist in the tests.

### PR DESCRIPTION
**Pull request by rudolfbyker**
Closes #282

### CODE REVIEW

File: test/facet-query-test.ts [hunk 1]
```diff
@@ -32,28 +27,6 @@ describe('Client#createQuery()', function () {
         mincount: 10,
         missing: true,
         method: 'fc',
-        date: [
```
Comment (kibertoad) [inline test/facet-query-test.ts:35]: why was this removed?

File: test/facet-query-test.ts [hunk 2]
```diff
@@ -109,24 +81,6 @@ describe('Client#createQuery()', function () {
         mincount: 10,
         missing: true,
         method: 'fc',
-        date: {
```
Comment (kibertoad) [inline test/facet-query-test.ts:112]: same

File: test/facet-query-test.ts (hunk 1 above)
Comment (rudolfbyker) [reply test/facet-query-test.ts:35]: The code ignores it. It's not covered in the types, or the actual function implementation, or in the test assertions. I'm assuming it refers to unimplemented functionality. Anyway, it should be a separate issue to implement that functionality if we need it.

**Review by kibertoad — APPROVED** [review]
